steps:
- task: prisma-cloud-compute-scan@3
  displayName: 'Prisma Cloud Compute Scan'
  inputs:
    twistlockService: 'sislam-pcc-selfhost'
    artifact: 'test-repo:latest'
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: shamsdocker
    dockerFile: Dockerfile
    imageName: 'test-repo:latest'
    includeSourceTags: true
    includeLatestTag: true